version = "1.0"

[metadata]
name = "Go Todo App Bug"
description = "Fix a bug in a Go Todo app using GORM and SQLite"
difficulty = "easy"

[verifier]
timeout_sec = 120

[agent]
timeout_sec = 300

[environment]
build_timeout_sec = 600
cpu = 2
memory_mb = 4906
storage_mb = 2048
